### ISSUE TITLE
Recommend ZGC or Shenandoah GC instead of custon G1GC tunings in "wrong GC" error to user

### ISSUE THREAD

**Issue by mkrupczak3** [aikar/timings#105]
Hey @aikar , 

Love your tool, it looks great and I'll definitely have to check it out if I host another server. 

May I suggest that you change some of your documentation and your "Wrong GC" error message to recommend the Shenandoah GC or ZGC instead of Java's default G1GC with custom tunings?

It's been a while since I've dorked with this, but I'm pretty sure I remember finding I had drastically better performance with the fancy new [Shenandoah GC](https://dzone.com/articles/java-garbage-collection-3) or [ZGC](https://docs.oracle.com/en/java/javase/14/gctuning/available-collectors.html#GUID-45794DA6-AB96-4856-A96D-FDE5F7DEE498) than with the old G1GC with similar custom tunings. 

Please let me know, however, if you have better information.

I've compiled my related thoughts here:
https://github.com/mkrupczak3/jvmperfopts/issues/1#issuecomment-699334194

**Comment by electronicboy** [comment]
These modern fancy collectors look nice on paper and even work amazingly
for some, there are many cases where these collectors fail to keep up,
impacting the server much harsher, and these states are not shown in the GC
metrics bean. Until these cases are detectable, it's pretty hard to
recommend it over something which works well enough for most, that we can
see if it's acting in a bit so great way

**Comment by aikar** [comment]
No because as cat mentioned, zgc is not recommended for most people and even those it can work for, jury is still out on is it worth it.

Zgc requires large heaps to be usable in minecraft high allocation rate.

Shen I don't know much about but until there's solid data at least somewhat close to g1s data I'm not going to recommend it.

Java is not designed to be 1 config fits all. Each app has has different usage patterns and that's why we want configurable gcs.


These 2 gc will work great for business apps but so far results are meh for mc.

If you are curious about lower level details please ask on discord

**Comment by aikar** [comment]
I saw your linked issue. Those tuning are pretty bad and stock Shen is likely an improvement over that, but note that my gc research for minecraft has been done over months of effort, thousands of servers.

I have the results to back it up. We know that that with my tuning you will have optimized gc behavior that does not cause tps loss or visible lag spikes, and aims to be effecient on cpu.

Minecraft is special and these timings accounts for that
