### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by TitanicFreak** [aikar/timings#15]
Hi,

As of recently, our servers been lagging quite alot, so we decided to check timings.

After loading and pasting timings, we noticed one thing. There seems to be alot of missing data, as quite well, nothing adds up for us.

The timings in question would be, http://timings.aikar.co/v2/?id=9f5d2d7f47b344859b564e3923e09448, as you can see its lagging. However the lag tab seems to make zero sense.

As you can see, the total %'s don't add up to 100% no matter how you look at it. For example, we have a 30% and 2 "15%" events near the top of the lag view. Which doesn't add up to 100% at all, no even close. And anything below that isn't relevant as it barely brings the total % any closer to 100%.

This basically means there's missing data from the looks of it, and I can't quite seem to find it. The issue also seems to effect the "all view" tab. Further confusing us.

If you can provide any insight on how to fix this, that would be awesome. (And yes, we have verbose off)

Thanks for reading,
Ryan - TitanicFreak

**Comment by aikar** [comment]
Turning Verbose on might help, but there is also a concept of "Self" time, and time spent in sub sections not currently timed. So do need to add a new row for "Self/Untimed" so thats clear.

In this case your issue seems to be around the scheduler. There is a hidden flag for filtering out the super small timings, but i dont think thats the case here.

So its not exactly a 'bug' here, just more so you hit something that uses excessive time that I hadnt seen before to make it worth adding a timing for that code.

I will leave this open and debug what may be taking up significant time when ever i'm at home sometime.

**Comment by meytro** [comment]
I have the same problem as @TitanicFreak 

Since 1.9 some data is missing, doesn't matter if I use Timings with Spigot or Timings v2 with Paper. It's hard to find the cause of lag if exactly these causes are not included.

**Comment by aikar** [comment]
I added "Self" time to timings now
