### ISSUE TITLE
How to use V1 instead of V2?

### ISSUE THREAD

**Issue by Agazed** [aikar/timings#16]
How do I revert back to the old Timings format, the new one looks horrendous no offense lol.

**Comment by aikar** [comment]
Sorry to be so blunt, but instead of providing useless feedback, why not say what you find unattractive?

Others prefer darker appearences.

But your only option to use v1 is to go back to Spigot.... but I do not recommend it. V1 has bugs and is no where near as good as v2. v2 is a gold mine of information where as v1 is just a few labels.

**Comment by Techcable** [comment]
v1 is to bukkit as v2 is to paperspigot

**Comment by Agazed** [comment]
Well to start, it's really hard to read when the page extends the full width of the browser (Especially on  high res screens, my god). Second, I don't really prefer the dark appearance for data reading. Also it's a bit buggy with a lot of missing values and useless strings of information.

I suggest adding an option to allow users to switch between the new and old versions. You even stated at the top of the page "This site is still under heavy development" so forcing users to use a format that still needs work isn't a good idea.

**Comment by Techcable** [comment]
He'res a tutorial from the paperspigot forums: https://aquifermc.org/threads/how-to-read-data-from-timings-v2.16/

**Comment by Agazed** [comment]
It's a 45 minute video...

Is it that hard to add a drop down menu to switch between new and old versions?

**Comment by aikar** [comment]
That's like asking for a switch to go between Electric and Gas on an all electric engine.

It's 2 completely different systems/engines. V2 shares almost nothing with V1.
V2 also covers nearly everything important v1 did already. The "development" part at this time is to add even more data results than v1 even had. It means its not even at its maximum potential. but its already way beyond the usefulness of V1.

V2 will help you identify lag problems that V1 can not ever do.

I'll never understand why people are so opposed to change that they are willing to use an inferior version just to avoid change.

We can add a max width, and your welcome to PR an alternate style sheet to turn the colors light instead of dark, but it needs to be done using SASS variables

**Comment by klugemonkey** [comment]
Anyway to scale the font size?  Seems a bit big and hard to read in v2 vs v1.  The plugins part I find the most useful since it narrows down the content to look at a specific plugin.  I think might need to work on the bounds some, since it's possible to look at a total for over a period of time which may result in bigger numbers, most of the time when looking at a range, should be using average and when looking at a specific point in time should be using total.   This might get lost on the GUI, since it's hard to know that the dots can be moved for the range.  If there is some way to tie the two together to be more intuitive it would help.  I get a lot of users that use it and really don't understand what the numbers represent, yet they have no problem complaining that a high percentage total over a range translates into poor performance.
