### ISSUE TITLE
High impossible numbers in graph

### ISSUE THREAD

**Issue by NoChanceSD** [aikar/timings#32]
https://timings.aikar.co/?id=5f4175315d364af4b7228f66c85cd65c

This happens pretty often, the graph reports ridiculously high numbers for entities, tile entities, etc
Also the number of loaded chunks seems to be wrong not only in that last bit but across all the graph.

**Comment by Brokkonaut** [comment]
Can confirm the wrong chunk count.

**Comment by aikar** [comment]
Chunk counts arent 'wrong', just wrongly labeled. It's no longer reporting chunks, but regions.

I need to modify paper to export chunk counts seperately from regions.

As for the high numbers, I recently put in some changes to Paper that I think will resolve that issue. I think its purely a bad export, so I changed the export process in build 1051, which you are not on, so please update and let me know if you run into it again.

but if you do, report it to Paper as the issue is on the server, not the web.

**Comment by NoChanceSD** [comment]
Alright, i wasn't sure where to report, thought it could be some graphic error.
