### ISSUE TITLE
Colors are confusing.

### ISSUE THREAD

**Issue by ZizzyZizzy** [aikar/timings#39]
https://timings.aikar.co/?id=edeb6ec5fe004dda9929004241737a15

~~Look at the first three points. It shows 19.42TPS, but yet reports a **56%** TPS loss. I'm not sure where that percentage is coming from, but 20 TPS dropped to 19.42 is certainly not a 56% drop in TPS.~~

Also, the yellow line has blue dots, but both colors are in the legend:
At first glance, one would be led to believe that yellow = tile entities, per the legend. However, if you look at the numbers that correspond to the massive drop of the yellow line, you quickly realize that it's the blue dots that correspond to the blue color in the legend, which is Entities, not tile entities. It's very confusing to have both colors on that line when both colors are in the legend.

**Comment by ZizzyZizzy** [comment]
Humm..That might be a very light greenish yellow, actually, but it still looks yellow and confuses the issue.

**Comment by aikar** [comment]
The TPS loss is accurate. It's an implementation detail on how Spigot/Paper work internally due to some work I contributed years ago.

In CraftBukkit/Vanilla you WOULD have had 56% TPS Loss. However in Spigot+, The server will maintain a record of lost TPS, and "make up" for it in upcoming ticks.

Basically, this prevents any random spike from causing TPS loss. The server has to maintain more TPS loss than make up time to actually lose TPS, but "often" spikes can trigger minimal TPS loss as seen with 19.42 TPS.

The colors, sure I'm open to PR's to adjust the schemes of the lines/dots (pref each data type would have a color scheme, and the dots would be a different shade of the lines color)

**Comment by ZizzyZizzy** [comment]
Interesting, thanks for the clarification.

The server owner told me he gives away a package with the /nuke command, which would account for all the TNT entities. Seems like a bad idea to me.
